### PR TITLE
Abstration Dialog

### PR DESCRIPTION
**Pull request by songurov**

### CODE REVIEW

**Comment by contrix09** [comment]
Hi. There are breaking changes (the last two commits) in this PR. I would really like to know what you have in mind or any reason why you made these changes.

**Comment by songurov** [comment]
Hi, I would like in ViewModel not to have a ref IU because UI Forms and ViewModel are separate layers and I think it would be convenient for the user to have the opportunity to have a DialogService with which they can inject into their project without having major complications like mvvmxcross, autofac, splat, etc.

The same idea I have with Theme as you want to be able to modify from ViewModel, the idea with Core came in order to be expanded and interlinked easily in layer different from UI.

**Comment by contrix09** [comment]
Hmm you're right about that, ViewModels should not use any UI references. Though I created `MaterialDialog.Instance` so that developers can also use this as an injectable service by doing the something like the following:
```c#
container.Register<IMaterialDialog>(() => MaterialDialog.Instance);
```
But the `IMaterialDialog` can be found under the `XF.Material.Forms.UI.Dialogs`, and the namespace exposes some UI components. I guess I have overlooked this.

Since the current implementation of the library is tightly bound on the UI layer, it may be a good idea to further abstact the current implementation by exposing only what is necessary.

And for the Theme configuration, how would you like the developers change this from the ViewModel?

Either way, I want to see how these new implementations will work. But I cannot merge them yet to the `dev` branch for these will cause some breaking changes. For now I am fixing some bugs and that is currently my priority. Perhaps you could create for now a branch for these refactorings, and we can help each other out.

**Comment by songurov** [comment]
image

as you see I should import ref in the project which as I said before I do not have to ref IU

**Comment by thiagoparabas** [comment]
Please, accept this is PR.

**Comment by contrix09** [comment]
Hi. Sorry but I cannot merge these changes. After some thinking, this library won't be supporting MVVM since it focuses solely on the UI layer. BUT it can be used in a MVVM project. The dialog service added here can be done in a MVVM project without having these changes implemented in this library.

Example:
Core Project Service Abstraction:
```c#
namespace Sample.Core.Services
{
     public interface IDialogService
     {
          Task ShowAlertAsync(string message);
     }
}
```
UI Project Service Implementation
```c#
namespace Sample.UI.Services
{
     public class DialogService : IDialogService
     {
          public Task ShowAlertAsync(string message) => MaterialDialog.Instance.AlertAsync(message);
     }
}
```
Register the service in your UI project using your IoC provider (e.g. Mvx.IoCProvider)
```c#
namespace Sample.UI
{
    public partial class App : MvxFormsApplication
    {
        public App()
        {
            this.InitializeComponent();

            XF.Material.Forms.Material.Init(this);

            Mvx.IoCProvider.RegisterSingleton<IDialogService>(new DialogService());
        }
    }
}
```

**Pull request closed without merging**
