### PR TITLE
MaterialTextField iOS Crash Fix

### PR DESCRIPTION
**Pull request by pedroreglero**
Xamarin Forms app crashing when these conditions met:

- Running on iOS device
- Page not presented yet
- You try to set Text Property of MaterialTextField

### CODE REVIEW

**Comment by martijn00** [comment]
@softlion what do you think of this PR?

**Comment by softlion** [comment]
First I think the issue is half real. 
I can't reproduce it myself (but i tried only on iOS simulator, though it should not change much).
But it may happen.

The resolution removes the animation completely. There are other places in code with animation, and they don't have the same issue ?

So my advice is this PR is incomplete.
Like for my rewrite on the MaterialDateField, this control should be rewritten correctly (and simplified).
It should detects when its displaying for the first time and should not trigger any animation, as this happens mostly offscreen.

**Comment by ghost** [comment]
> First I think the issue is half real.
> I can't reproduce it myself (but i tried only on iOS simulator, though it should not change much).
> But it may happen.
> 
> The resolution removes the animation completely. There are other places in code with animation, and they don't have the same issue ?
> 
> So my advice is this PR is incomplete.
> Like for my rewrite on the MaterialDateField, this control should be rewritten correctly (and simplified).
> It should detects when its displaying for the first time and should not trigger any animation, as this happens mostly offscreen.

Ye, this solution might be temporal, it makes the plugin usable in REAL iPhone devices, I tried in simulator and it didn't crash.
Feel free to come up with something that checks if the page is presented or similar.
The problem was very annoying to me, I could not set the Text of a MaterialTextField in for example the constructor of the page if the app was running on iOS, so this was the quickest solution I've found.

P.D.: This is another GitHub account.

**Comment by martijn00** [comment]
Yeah i was thinking the same. This is not a good enough solution. Can you open a new PR with a better implementation? I'll close this one for now.

**Comment by pedroreglero** [comment]
> Yeah i was thinking the same. This is not a good enough solution. Can you open a new PR with a better implementation? I'll close this one for now.

This solution works for me right now.
I don't plan on spending time getting the animation to work since it is such a small difference visual-wise.
If I decide to make the animation work again, i'll make a PR.

Thank You.

**Comment by softlion** [comment]
@martijn00 The problem MartinJ is that pedro is right. This code does crash on ios device. And the animation is not noticeable.

**Comment by martijn00** [comment]
Hmm right. The branch is deleted, can you reopen?

**Comment by pedroreglero** [comment]
> Yeah i was thinking the same. This is not a good enough solution. Can you open a new PR with a better implementation? I'll close this one for now.

I think it's done now.

**Comment by pedroreglero** [comment]
> Hmm right. The branch is deleted, can you reopen?

I think it's done now.

**Comment by softlion** [comment]
Note that it won’t crash in release mode on a real device.

**Comment by pedroreglero** [comment]
> Note that it won’t crash in release mode on a real device.

hmm. That's weird.
It's annoying anyway to debug the app.

**Pull request closed without merging**
